In [50]:
#importing libraries
import matplotlib.pyplot as plt
import pandas as pdA
import numpy as np
import seaborn as sns

In [5]:
# load datasets
df=pd.read_csv("F:\coe_practice\Salary datasets .csv")
df

     years_experience  salary
0                 3.7   32610
1                 9.5   61447
2                 7.3   51729
3                 6.0   42857
4                 1.6   30797
..                ...     ...
195               3.5   29528
196               7.3   48695
197               9.0   57860
198               8.9   58983
199               7.8   57526

[200 rows x 2 columns]

In [6]:
df.head

<bound method NDFrame.head of      years_experience  salary
0                 3.7   32610
1                 9.5   61447
2                 7.3   51729
3                 6.0   42857
4                 1.6   30797
..                ...     ...
195               3.5   29528
196               7.3   48695
197               9.0   57860
198               8.9   58983
199               7.8   57526

[200 rows x 2 columns]>

In [7]:
df.sample(10)

     years_experience  salary
155               2.4   27025
34                9.7   63070
182               9.2   62325
136               5.2   42243
148               0.5   17763
97                4.3   38565
104               9.1   62751
0                 3.7   32610
39                4.4   40369
35                8.1   54232

In [9]:
#divide data into x and y
x=df['years_experience']
y=df['salary']
x,y

(0      3.7
 1      9.5
 2      7.3
 3      6.0
 4      1.6
       ...
 195    3.5
 196    7.3
 197    9.0
 198    8.9
 199    7.8
 Name: years_experience, Length: 200, dtype: float64,
 0      32610
 1      61447
 2      51729
 3      42857
 4      30797
        ...
 195    29528
 196    48695
 197    57860
 198    58983
 199    57526
 Name: salary, Length: 200, dtype: int64)

In [51]:
# train and test splitting
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2,random_state=42)

In [59]:
x_train = x_train.values.reshape(-1, 1)
x_test  = x_test.values.reshape(-1, 1)

In [60]:
from sklearn.linear_model import LinearRegression
# create model object
lr = LinearRegression()
# train model
model=lr.fit(x_train, y_train)

In [40]:
y_pred=model.predict(x_test.reshape(-1,1))

In [41]:
y_pred

array([40247.41443883, 26199.37750596, 45685.3642193 , 28918.35239619,
       18495.61531696, 57467.58874365, 62905.53852412, 48857.50159124,
       47498.01414612, 47951.17662783, 24386.72757913, 59733.40115218,
       56108.10129853, 34356.30217666, 55201.77633512, 35715.78962178,
       22120.9151706 , 24386.72757913, 32996.81473154, 21214.59020719,
       28465.18991448, 31637.32728642, 20308.26524378, 43419.55181077,
       42513.22684736, 35715.78962178, 32090.48976813, 54295.45137171,
       37528.4395486 , 23480.40261572, 50216.98903636, 37528.4395486 ,
       59733.40115218, 51123.31399977, 59280.23867047, 59280.23867047,
       32543.65224984, 49763.82655465, 22120.9151706 , 52935.96392659])

In [43]:
data=pd.DataFrame({'actual':y_test,'predicted':y_test})
data.head(10)

     actual  predicted
95    38090      38090
15    31790      31790
30    42237      42237
158   28147      28147
128   18791      18791
115   52860      52860
69    56948      56948
170   46145      46145
174   50724      50724
45    48161      48161

In [46]:
data=pd.DataFrame({'actual':y_test,'predicted':y_pred,'difference':y_test- y_pred})
data.head(10)

     actual     predicted   difference
95    38090  40247.414439 -2157.414439
15    31790  26199.377506  5590.622494
30    42237  45685.364219 -3448.364219
158   28147  28918.352396  -771.352396
128   18791  18495.615317   295.384683
115   52860  57467.588744 -4607.588744
69    56948  62905.538524 -5957.538524
170   46145  48857.501591 -2712.501591
174   50724  47498.014146  3225.985854
45    48161  47951.176628   209.823372

In [54]:
from sklearn.metrics import mean_squared_error, r2_score

In [57]:
r2=r2_score(y_test, y_pred)
MSE=mean_squared_error(y_test,y_pred)

In [58]:
MSE

9762990.417736227