In [5]:
import pandas as pd
Uber_data=pd.read_csv("Uber_Drives_2016.csv")
Uber_data.head() #first 5 rows

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [6]:
Uber_data.tail()# last 5 rows

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [7]:
print(Uber_data.shape)# no of rows and columns

(1156, 7)

In [8]:
print(Uber_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   START_DATE*  1156 non-null   object
 1   END_DATE*    1155 non-null   object
 2   CATEGORY*    1155 non-null   object
 3   START*       1155 non-null   object
 4   STOP*        1155 non-null   object
 5   MILES*       1156 non-null   float64
 6   PURPOSE*     653 non-null    object
dtypes: float64(1), object(6)
memory usage: 63.3+ KB
None

In [9]:
print(Uber_data.isnull().sum())

START_DATE*      0
END_DATE*        1
CATEGORY*        1
START*           1
STOP*            1
MILES*           0
PURPOSE*       503
dtype: int64

In [10]:
null_rows=Uber_data[Uber_data.isnull().any(axis=1)]
print(null_rows)

           START_DATE*         END_DATE* CATEGORY*            START*  \
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce
32      1/19/2016 9:09    1/19/2016 9:23  Business       Whitebridge
85      2/9/2016 10:54    2/9/2016 11:07  Personal       Whitebridge
86      2/9/2016 11:43    2/9/2016 11:50  Personal        Northwoods
87      2/9/2016 13:36    2/9/2016 13:52  Personal        Tanglewood
...                ...               ...       ...               ...
1066  12/19/2016 14:37  12/19/2016 14:50  Business  Unknown Location
1069  12/19/2016 19:05  12/19/2016 19:17  Business         Islamabad
1071   12/20/2016 8:49   12/20/2016 9:24  Business  Unknown Location
1143  12/29/2016 20:53  12/29/2016 21:42  Business           Kar?chi
1155            Totals               NaN       NaN               NaN

                    STOP*   MILES* PURPOSE*
1             Fort Pierce      5.0      NaN
32    Lake Wellingborough      7.2      NaN
85             Northwoods      5.3      NaN
86             Tanglewood      3.0      NaN
87                Preston      5.1      NaN
...                   ...      ...      ...
1066     Unknown Location      5.4      NaN
1069     Unknown Location      2.2      NaN
1071           Rawalpindi     12.0      NaN
1143     Unknown Location      6.4      NaN
1155                  NaN  12204.7      NaN

[503 rows x 7 columns]

In [11]:
null_rows=Uber_data[Uber_data['START_DATE*'].isnull()]
print(null_rows)

Empty DataFrame
Columns: [START_DATE*, END_DATE*, CATEGORY*, START*, STOP*, MILES*, PURPOSE*]
Index: []

In [12]:

Uber_data = Uber_data.rename(columns={'START_DATE*': 'START_DATE','END_DATE*': 'END_DATE','START*': 'START'})
Uber_data

,START_DATE,END_DATE,CATEGORY*,START,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
...,...,...,...,...,...,...,...
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [13]:
Uber_data.head()

,START_DATE,END_DATE,CATEGORY*,START,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [14]:
Uber_data.tail()

,START_DATE,END_DATE,CATEGORY*,START,STOP*,MILES*,PURPOSE*
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [15]:
Uber_data.iloc[0] #first_row data and access specific row

START_DATE    1/1/2016 21:11
END_DATE      1/1/2016 21:17
CATEGORY*           Business
START            Fort Pierce
STOP*            Fort Pierce
MILES*                   5.1
PURPOSE*      Meal/Entertain
Name: 0, dtype: object

In [30]:
Uber_data.iloc[2:8] #row 2-7

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting

In [ ]:
Uber_data.iloc[2:8,1:5] #row 2-7 col-1-4

In [ ]:
Uber_data['START_DATE']

In [21]:
import pandas as pd
Uber_data=pd.read_csv("Uber_Drives_2016.csv")

In [26]:
Uber_data[['START_DATE*','STOP*','PURPOSE*']]

           START_DATE*             STOP*         PURPOSE*
0       1/1/2016 21:11       Fort Pierce   Meal/Entertain
1        1/2/2016 1:25       Fort Pierce              NaN
2       1/2/2016 20:25       Fort Pierce  Errand/Supplies
3       1/5/2016 17:31       Fort Pierce          Meeting
4       1/6/2016 14:42   West Palm Beach   Customer Visit
...                ...               ...              ...
1151  12/31/2016 13:24  Unknown Location   Temporary Site
1152  12/31/2016 15:03  Unknown Location          Meeting
1153  12/31/2016 21:32           Gampaha   Temporary Site
1154  12/31/2016 22:08         Ilukwatta   Temporary Site
1155            Totals               NaN              NaN

[1156 rows x 3 columns]

In [25]:
Uber_data.loc[[1,2,3],['START*','STOP*','MILES*']]

        START*        STOP*  MILES*
1  Fort Pierce  Fort Pierce     5.0
2  Fort Pierce  Fort Pierce     4.8
3  Fort Pierce  Fort Pierce     4.7

In [35]:
temp=pd.DataFrame({'A':[1],'B':[5],'c':['2025-1-19']})
temp

   A  B          c
0  1  5  2025-1-19

In [36]:
temp.dtypes

A     int64
B     int64
c    object
dtype: object

In [39]:
temp['c']=pd.to_datetime(temp['c'])
temp.dtypes

A             int64
B             int64
c    datetime64[ns]
dtype: object

In [66]:
Uber_data[['START_DATE*','END_DATE*']]=pd.to_datetime(Uber_data[['START_DATE*','END_DATE*']])	
Uber_date.dtypes

ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day,month,year] is missing

In [43]:
temp['A']=temp['A'].astype(str)
temp.dtypes

A            object
B             int64
c    datetime64[ns]
dtype: object

In [53]:
temp1=temp
temp1['c'] = pd.to_datetime(temp1['c'], format="%d-%m-%y")
temp1.dtypes

A            object
B             int64
c    datetime64[ns]
dtype: object

In [52]:
#1.Boolean indexing and filtering
a=[Uber_data['MILES*']>6]
a

[0       False
 1       False
 2       False
 3       False
 4        True
         ...
 1151    False
 1152     True
 1153     True
 1154     True
 1155     True
 Name: MILES*, Length: 1156, dtype: bool]

In [59]:
a=Uber_data[(Uber_data['MILES*']>6)&(Uber_data['MILES*']<8)]
a

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting
13,1/11/2016 8:55,1/11/2016 9:21,Business,East Harlem,NoMad,6.4,Temporary Site
32,1/19/2016 9:09,1/19/2016 9:23,Business,Whitebridge,Lake Wellingborough,7.2,NaN
...,...,...,...,...,...,...,...
1123,12/27/2016 16:34,12/27/2016 16:58,Business,Unknown Location,Kar?chi,7.9,Meeting
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Between Offices
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,NaN
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site

In [61]:
df3=Uber_data.loc[Uber_data['START*']=="New York"]
df3

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting
106,2/14/2016 16:35,2/14/2016 17:02,Business,New York,Long Island City,13.0,Meeting
423,6/10/2016 15:19,6/10/2016 16:28,Business,New York,Jamaica,16.3,Meeting

In [64]:
Uber_data.loc[Uber_data['START*'].isin(['New york','Cary'])]

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meal/Entertain
30,1/18/2016 14:55,1/18/2016 15:06,Business,Cary,Cary,4.8,Meal/Entertain
34,1/20/2016 10:36,1/20/2016 11:11,Business,Cary,Raleigh,17.1,Meeting
...,...,...,...,...,...,...,...
1049,12/13/2016 20:20,12/13/2016 20:29,Business,Cary,Cary,4.1,Meal/Entertain
1050,12/14/2016 16:52,12/14/2016 17:10,Business,Cary,Cary,3.4,NaN
1051,12/14/2016 17:22,12/14/2016 17:34,Business,Cary,Cary,3.3,NaN
1052,12/14/2016 17:50,12/14/2016 18:00,Business,Cary,Morrisville,3.0,Meal/Entertain
1054,12/15/2016 14:20,12/15/2016 14:54,Business,Cary,Morrisville,10.6,Meeting

In [8]:
def1=Uber_dataloc[(Uber_data['MILES*']>10)&(Uber_data['START*'].isin([Cary','Morris'])]

SyntaxError: unterminated string literal (detected at line 1) (941318015.py, line 1)

In [7]:
import numpy as np
Uber_data['MILE_CAT'] = np.where(Uber_data['MILES*'] > 100, "Long trip", "Short trip")
Uber_data.head()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*,MILE_CAT
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,Short trip
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN,Short trip
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,Short trip
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting,Short trip
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,Short trip

In [13]:
conditions=[(Uber_data['MILES*']>100),(Uber_data['MILES*']>50) & (Uber_data['MILES*']<=100),(Uber_data['MILES*']<=50)]
categories=["long trip","medium trip","short trip"]
Uber_data["MILE_CART"]=np.select(conditions, categories,default="unkown")
Uber_data

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*,MILE_CAT,MILE_CART
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,Short trip,short trip
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN,Short trip,short trip
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,Short trip,short trip
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting,Short trip,short trip
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,Short trip,medium trip
...,...,...,...,...,...,...,...,...,...
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site,Short trip,short trip
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting,Short trip,short trip
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site,Short trip,short trip
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site,Short trip,short trip
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN,Long trip,long trip